version: '3'

networks:
  rest-fuzzing:
    driver: bridge

services:
  db:
    image: bungdanar/mysql-rest-fuzzing:extended
    restart: 'no'
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    networks:
      - rest-fuzzing

  webapi:
    image: bungdanar/python-rest-fuzzing:extended
    depends_on:
      - db
    restart: 'no'
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - './logs:/app/logs'
    env_file:
      - .env
    networks:
      - rest-fuzzing
    ports:
      - '${DOCKER_PORT}:5000'
    command: bash -c "while !</dev/tcp/db/3306; do sleep 1; done; gunicorn -w 4 -b 0.0.0.0:5000 'app:create_app()' --access-logfile -"
