"""Add more fields to product

Revision ID: 01b050a0a9b3
Revises: e38d5720c3ce
Create Date: 2023-05-22 14:55:17.875258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01b050a0a9b3'
down_revision = 'e38d5720c3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('weight', mysql.DOUBLE(asdecimal=True, unsigned=True), nullable=False))
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('published')
        batch_op.drop_column('note')
        batch_op.drop_column('weight')
        batch_op.drop_column('description')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
