"""Add name and sku fields to product

Revision ID: 298be0df4b92
Revises: 8f3527ce0bab
Create Date: 2023-05-22 13:49:06.256930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298be0df4b92'
down_revision = '8f3527ce0bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sku')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
