"""Add product

Revision ID: b22ad93da9d4
Revises: 
Create Date: 2023-05-22 16:42:35.881236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b22ad93da9d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('regular_price', mysql.DECIMAL(unsigned=True, precision=19, scale=4), nullable=False),
    sa.Column('discount_price', mysql.DECIMAL(unsigned=True, precision=19, scale=4), nullable=False),
    sa.Column('quantity', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('weight', mysql.DOUBLE(asdecimal=True, unsigned=True), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
