"""Add regular and discount price to product

Revision ID: e38d5720c3ce
Revises: 09b89d81821e
Create Date: 2023-05-22 13:54:06.712591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e38d5720c3ce'
down_revision = '09b89d81821e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regular_price', mysql.DECIMAL(unsigned=True, precision=19, scale=4), nullable=False))
        batch_op.add_column(sa.Column('discount_price', mysql.DECIMAL(unsigned=True, precision=19, scale=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discount_price')
        batch_op.drop_column('regular_price')

    # ### end Alembic commands ###
